### ISSUE TITLE
redesign follow up

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#591]
- venue and event description should be darker/ have more contrast
- make active menu entry more visible in admin
  
  > @christopheschwyzer could you find a neat way to make the _active_ menu entry more visible in the admin? Change the background? 
  > <img width="229" alt="screen shot 2016-09-25 at 19 11 59" src="https://cloud.githubusercontent.com/assets/360800/18816936/01866026-8354-11e6-8fce-4942fbc188b0.png">

**Comment by NicolasSchmutz** [comment]
@christopheschwyzer changed this issue to gather redesign adjustments.

cc @njam

**Comment by trampy** [comment]
suggestion for UI: for events where there is no song provided, also display the "play"-icon, but with a very low opacity and without link. wdyt?

**Comment by NicolasSchmutz** [comment]
@trampy I'm not convinced about the idea as I don't see the value. It would be very strange if a day has no song.
How about we rather do one of the following:
- change the UI so that the play button is less prominent and the text has more space.
- find a solution for: https://github.com/denkmal/denkmal.org/issues/501

**Comment by trampy** [comment]
Totally agree, if a day has no song it would look strange.
Just thought it would be nice to have some kind of replacement for the Play-button, when there is no song. Not sure what that could be though. Will also think about it :)

Regarding #501 <https://github.com/denkmal/denkmal.org/issues/501>: Yes, would be great to link the Play-button with a soundcloud or youtube-link. I can do some research when I’m back in Graz!

**Comment by christopheschwyzer** [comment]
I suggest we rethink the event design. 
- Make play button less prominent
- Make Location less prominent -> rather the event title?
- Consider _popup_ instead of _slide-down_
- Consider making whole event tile clickable (remove links?)

**Comment by NicolasSchmutz** [comment]
👍 let's discuss when I'm back

**Comment by NicolasSchmutz** [comment]
Unsorted notes/ideas from a discussion with Reto and Christophe (IIRC):
- remove songs completely
- remove links completely
- add event link (facebook for example)
- make event section clickable
 - open information section per event with location, time, now, event link, ...
- simplify genre by tags(?) and allow only a few
- display genre next to location or make it more prominent
- introduce sorting: 
 - favourite locations (per user) on top 
 - followed by starred (suggested) events
 - followed by the rest sorted by location?
- add fancy machine learning for favourite locations and suggest other locations with a few question
- improve scrolling

The first three would save a lot time maintaining the site. The rest is mainly UX improvement. 

@njam @christopheschwyzer anything else? :)
cc @trampy

**Comment by trampy** [comment]
Hey everyone, Denkmal is up and running in Graz for a few weeks. The general feedback is very good, I'm happy we did it, big thanks to everyone :) Here are some of my thoughts regarding the suggestions above:

- remove songs completely
I wouldn't do that, since most people told me that this feature is what makes Denkmal unique. However, making the process easier would be awesome. I download all the songs from three sources: Soundcloud, Bandcamp, Youtube. Do you think it would be possible if the admin just provides the links to the songs, and a script automatically downloads them from the source and re-uploads them to Denkmal? That would safe a lot of time.
- remove links completely
Thought about that too, since I am not sure how many people really use the links... 
- add event link (facebook for example)
This would be a great replacement for the links. So there would just be one link per event. In most cases this would be a link to the Facebook event, but it could also be a link to another website with information about the event.
- make event section clickable
   - open information section per event with location, time, now, event link, ...
No opinion on this topic.
- simplify genre by tags(?) and allow only a few
Thought about that too, but I'm not sure if it would actually safe time. And somehow I like inventing weird genres ;) 
- display genre next to location or make it more prominent
If we remove the links, then we would just have plain text in the event descriptions, which probably looks boring. So accentuating the genres would be cool.
- introduce sorting:
Regarding sorting I have a clear opinion. If I had to choose I would sort the events by start time. Additionally I would put all events with Play-button to the top, all the others to the bottom. It would look cleaner in my opinion.
- add fancy machine learning for favourite locations and suggest other locations with a few question
Not sure if users actually need that feature.
- improve scrolling
Would be great, it sometimes bugs a little bit.

Two additional things:

- Denkmal Now: The text and the photo-icon nearly look like stickers. Suggestion: Simply put those two icons in a separate row.
- Scraping: I would prefer if scraped events that take place within the next 1-2 days, aren't automatically displayed since I often have to remove them. I would suggest to display events 48h after they were scraped.

**Comment by NicolasSchmutz** [comment]
@trampy thanks a lot for the input! 
I suggest making a small "workshop" (~1h call) where we define the structure of the next version and set priorities and later do a hackathon where we implement everything.
I'm a bit busy now and in January and also some time on vacation. How about we do:
- Workshop over Christmas 
- Hackathon maybe in February or March. For example to http://www.wissifluh.ch/

@christopheschwyzer @njam it would be great if you could join as well!

**Comment by christopheschwyzer** [comment]
sgtm

**Comment by NicolasSchmutz** [comment]
sent invite for the workshop. lmk if it doesn't fit.

**Comment by trampy** [comment]
hangout-session over christmas sounds good! 
@NicolasSchmutz, can you please resend the invite?

**Comment by NicolasSchmutz** [comment]
Other ideas from our discussion:
- keep music but less prominent (remove empty space if there are no songs) 
- add icons for different event types (disco, live band, vernissage...)
- add venue logo
- add to home screen guide
- sorting after "favourite" and "starred" could be also chronological by time
- ...?

Organisational
- Hackathon will be on Feb 24.-26.
- Alex and I will research a location in January

Ideas, input and first drafts are welcome! :)

**Comment by christopheschwyzer** [comment]
Did a quick twitter inspired draft to think about. 
<img width="542" alt="screen shot 2016-12-27 at 15 44 59" src="https://cloud.githubusercontent.com/assets/1888817/21501825/907c1a56-cc4b-11e6-8185-686be90dd654.png">

**Comment by christopheschwyzer** [comment]
I also noticed that the map link is just coordinates. Is it possible to get a "google" compatible location? See example:
![screen-shot-2016-12-27-at-15 53 42](https://cloud.githubusercontent.com/assets/1888817/21502014/0b7f9df8-cc4d-11e6-9bc8-979ab4d66d84.jpg)

**Comment by NicolasSchmutz** [comment]
👍 for google maps compatible locations: https://github.com/denkmal/denkmal.org/issues/623

I really like the idea/direction of the twitter inspired draft! The text of the event is in focus but everything else is easily accessible (denkmal now, music, fb link, location,...). The only minor downside is that users have to scroll more. We need to experiment a bit more with the Band/DJ names as they sometimes need much more space:
<img width="708" alt="screen shot 2016-12-31 at 17 22 24" src="https://cloud.githubusercontent.com/assets/4020326/21578373/bf02851a-cf7d-11e6-9aee-7c63b6c853da.png">


I thought about the events text a bit more (title, acts, genre). I think splitting them up into three fields or by pressing enter (new line) in the admin would make sense. This way we could detect the different parts and design them differently. In the end it's the same effort as we have now with arranging it (with : and .).

**Comment by NicolasSchmutz** [comment]
Reto and I made a plan for the hackathon and created tickets for it. All of the above is either obsolete or was moved to other tickets.

Hackathon milestones: https://github.com/denkmal/denkmal.org/milestone/2
