### ISSUE TITLE
Mini-bug: Twitter & FB-links redirect to regions page

### ISSUE THREAD

**Issue by trampy** [denkmal/denkmal.org#599]
When you click on a link like this:
https://t.co/exzAxx3JLK

You get redirected here:
<img width="414" alt="bildschirmfoto 2016-09-30 um 13 02 39" src="https://cloud.githubusercontent.com/assets/18462266/18989824/60b720f4-870e-11e6-8b3e-808556cf6cb0.png">

Happens also when you are located in Graz. For the Basel-site it seems to work though.

**Comment by njam** [comment]
This link seems to be a shortlink for "http://denkmal.org/events?date=2016-9-29". Where is it from?

It seems to me like the geo detection doesn't work for you. What happens if you go to https://www.denkmal.org/ - do you get redirected to the Graz page, or do you see the regions selection? What is your IP address?

**Comment by trampy** [comment]
This link comes from the automatic Facebook/Twitter-Post on https://www.facebook.com/denkmal.graz/ <https://www.facebook.com/denkmal.graz/>
It happened for me (on the computer from Basel) and for a friend (on the phone from Graz).
My IP-adress is 84.227.83.165.

**Comment by njam** [comment]
The problem seems that the site was not enabled yet when that tweet was sent.
- 18:00 Tweet sent: https://twitter.com/denkmal_graz/status/781523938375561216
- 21:08 Graz site enabled: https://github.com/denkmal/denkmal.org/pull/596

Since the site was not enabled yet the link was created for the non-regional site:
![screen shot 2016-09-30 at 16 38 19](https://cloud.githubusercontent.com/assets/360800/18995408/50d37c8c-872c-11e6-97af-303ca1f2fbdf.png)

As you can see with this example for Basel usually it creates links to the regional site:
![screen shot 2016-09-30 at 16 38 31](https://cloud.githubusercontent.com/assets/360800/18995417/61052fb0-872c-11e6-953d-ced2993fd637.png)

**Comment by trampy** [comment]
ahh alright, that makes sense! 
thanks for troubleshooting, reto :)
