### ISSUE TITLE
Acceptance test, check performance

### ISSUE THREAD

**Issue by christopheschwyzer** [denkmal/denkmal.org#682]
Possible improvements:
- Lazy load map images
- Render `Denkmal_Component_EventDetails` on demand only

**Comment by christopheschwyzer** [comment]
fyi @NicolasSchmutz @njam 
Testing: Network 4G, Cache disabled.

With  `Denkmal_Component_EventDetails` prerendered
<img width="626" alt="screen shot 2017-03-03 at 16 24 08" src="https://cloud.githubusercontent.com/assets/1888817/23556823/30959718-002e-11e7-9455-0fec41c477aa.png">

With  `Denkmal_Component_EventDetails` prerendered, without map image
<img width="605" alt="screen shot 2017-03-03 at 16 29 05" src="https://cloud.githubusercontent.com/assets/1888817/23556972/a33936e4-002e-11e7-9076-f43a36c5ea1f.png">

Without  `Denkmal_Component_EventDetails`
<img width="592" alt="screen shot 2017-03-03 at 16 20 13" src="https://cloud.githubusercontent.com/assets/1888817/23556841/425d7c04-002e-11e7-864d-a55b72a605ca.png">

Interestingly online version is much faster (due local server performance? Less events?)
<img width="563" alt="screen shot 2017-03-03 at 16 33 59" src="https://cloud.githubusercontent.com/assets/1888817/23557144/535fedd8-002f-11e7-95cd-951aae633293.png">

…suggest rendering on demand. Investigating some more.

**Comment by christopheschwyzer** [comment]
Lazy-loading map images, no additional cmp for details:
<img width="586" alt="screen shot 2017-03-04 at 14 27 44" src="https://cloud.githubusercontent.com/assets/1888817/23579123/efd3b17e-00e6-11e7-98ba-a41ad88644d5.png">

**Comment by njam** [comment]
"Lazy-loading map images" looks strange, it's also 2.3 MB like the original measurement. It should be more like 0.7MB?
Did you check also the swiping performance? How smoothly the left/right swiping works compared to the current version?

**Comment by christopheschwyzer** [comment]
Hm. But DOM is loaded <4s. Would you only load the images on demand then? Will do some more acceptance testing…

**Comment by christopheschwyzer** [comment]
Some stuff:
- Performance on newer phones seems ok (tested with Browserstack only)
- The starring animation isn't fixed yet :/ (When opening/closing floatbox it will trigger the animation)
- Maybe we use a light gray bar for the date - but it will be a bit weird when swiping:
<img width="489" alt="screen shot 2017-03-05 at 00 43 43" src="https://cloud.githubusercontent.com/assets/1888817/23583168/e7f7a662-013c-11e7-84af-be9b6b30fdc9.png">
- Maybe different map theme

**Comment by njam** [comment]
I will try to test it with some real phones during the day today. I'll let you know.

**Comment by njam** [comment]
I compared the swiping experience of the old and new event list on an S6 Edge. The new list's animation is much smoother! I imagine it's because of the box shadows we were previously using on each event entry.

I'm not sure what causes the difference of production to local. You could set `development => false` in `puppet/environments/development/manifests/site.pp` and then `vagrant provision` to get a more similar behaviour like on production. But it's probably more precise to compare the old code with the new code in the local environment, using the same database state.

(It's a bit difficult to get back the old event list code to compare it with the current one. Maybe next time we should create a new branch, instead of merging it into master before it's fully ready.)

Notes:
- The event list entry is getting *popped out* when showing the details, which means there's a hole in the list in the background. How about making the background fully white, using floatbox' "fullscreen" styling? This comes with the downside that the user can't close the floatbox anymore by clicking on the background. How about rendering the event HTML twice?
- I would try loading the map only when the details are opened, so we don't load 1.5MB for nothing. 
- I will add the song-player to the header bar, so you can style it.
- Did you try using ♥ instead of ♡ for the promoted events?

**Comment by christopheschwyzer** [comment]
> Maybe next time we should create a new branch, instead of merging it into master before it's fully ready.

Agree, my bad, it was a bit overhasty to merge into master. Can we easily create a "feature" branch on upstream and make PRs to it?

> Did you try using ♥ instead of ♡ for the promoted events?

Yeah had a hard time :)

<img width="317" alt="screen shot 2017-03-06 at 18 02 01" src="https://cloud.githubusercontent.com/assets/1888817/23620475/4da19bb6-0297-11e7-80c9-12bd3ef9965f.png">
<img width="315" alt="screen shot 2017-03-06 at 18 03 00" src="https://cloud.githubusercontent.com/assets/1888817/23620476/4da58582-0297-11e7-8bd3-ab46a27b97b1.png">


Still not sure. Votes? @NicolasSchmutz wdyt?

**Comment by christopheschwyzer** [comment]
I thought the filled-out one was a bit strong, especially next to the music icon. On the other hand - the outlined one creates the impression it'd be clickable like the star.

**Comment by NicolasSchmutz** [comment]
😬
I would go with ♥. Usually there will be just one per day and I think it's okay if it is stronger than the music icon...

**Comment by njam** [comment]
Some performance optimizations made here: https://github.com/denkmal/denkmal.org/pull/714

Overall seems fine, let's open separate tickets if something pops up.
