### ISSUE TITLE
Floatbox/EventDetails design

### ISSUE THREAD

**Issue by christopheschwyzer** [denkmal/denkmal.org#725]
I'm not so happy with the current version floatbox. I suggest:
- Add a floatbox "opening" transition (scale?)
- The closing button looks weird and is in the wrong position (on mobile) -> maybe have big "close button" on the bottom of the floabox?

I will experiment a bit.

**Comment by njam** [comment]
It's a pity that the click feedback is not visible when clicking on an event. Therefore as a user it's not clear to me why the floatbox opened, and what it is about (did I click on the genre? or the venue?).

Maybe we should delay the opening of the floatbox by a few milliseconds, so that the click feedback is visible. A fade-in animation could also help.

**Comment by christopheschwyzer** [comment]
Agree
