### ISSUE TITLE
Improve eventList sorting 

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#731]
Currently we have three different sorting categories for the eventList:
- venue-bookmark (individually)
- promoted
- alphabetically by venue name

I think this is too much and it leads to incomprehensible listing. @trampy I know you are in favour of displaying the promoted events. How about we keep the heart icon for the promoted events but don't list it on the top? The promoted events would also should up in the alphabetical order.
In addition we could display  nonetheless an explanation about the heart in the event detail list.

wdyt?

**Comment by trampy** [comment]
I agree that the current way of sorting is too confusing. Including promoted events in the alphabetical sorting makes more sense for now.

However, two suggestions for the future since I love to have the opportunity to promote events:

- Would it be possible to choose for each region, whether the promoted events show up in **alphabetical order** or at the **very top**? 
- And could we maybe find another way to highlight promoted events? In my opinion the old way (with the yellow bar) was a bit more distinctive.

**Comment by njam** [comment]
Another option we briefly discussed: write in small letters below the event's text:
*Recommended by Denkmal.org*
This way it is very obvious what's happening.

**Comment by NicolasSchmutz** [comment]
>I agree that the current way of sorting is too confusing. 

>Would it be possible to choose for each region, whether the promoted events show up in alphabetical order or at the very top?

@trampy isn't this inconsistent? ;)
I would try to avoid having different versions and rather try to find a consensus.
wdyt about Reto's comment?

**Comment by trampy** [comment]
Haha, hm... I don't think so ;) What I was trying to say...

Either it should be this way (A):

- venue-bookmark (individually)
- alphabetically by venue name (including promoted events)

Or this way (B):

- promoted events (with obvious labeling, as suggested by @njam)
- venue-bookmark (individually)
- alphabetically by venue name

The possibility (as an admin) to choose which way it is would be great, otherwise option A is also fine with me of course.

**Comment by NicolasSchmutz** [comment]
How about option A with obvious labeling, as Reto suggested?
So the promoted events would be in the alphabetical order like all other venues but have a more obvious indication that they are promoted by us.

**Comment by trampy** [comment]
sgtm!

**Comment by NicolasSchmutz** [comment]
ok closing in favour of https://github.com/denkmal/denkmal.org/issues/737 and https://github.com/denkmal/denkmal.org/issues/738
